// Header Actions
export const FETCH_HEADER_REQUEST = 'FETCH_HEADER_REQUEST';
export const FETCH_HEADER_SUCCESS = 'FETCH_HEADER_SUCCESS';
export const FETCH_HEADER_FAILURE = 'FETCH_HEADER_FAILURE';

export const ADD_HEADER_ITEM_REQUEST = 'ADD_HEADER_ITEM_REQUEST';
export const ADD_HEADER_ITEM_SUCCESS = 'ADD_HEADER_ITEM_SUCCESS';
export const ADD_HEADER_ITEM_FAILURE = 'ADD_HEADER_ITEM_FAILURE';

export const UPDATE_HEADER_ITEM_REQUEST = 'UPDATE_HEADER_ITEM_REQUEST';
export const UPDATE_HEADER_ITEM_SUCCESS = 'UPDATE_HEADER_ITEM_SUCCESS';
export const UPDATE_HEADER_ITEM_FAILURE = 'UPDATE_HEADER_ITEM_FAILURE';

export const DELETE_HEADER_ITEM_REQUEST = 'DELETE_HEADER_ITEM_REQUEST';
export const DELETE_HEADER_ITEM_SUCCESS = 'DELETE_HEADER_ITEM_SUCCESS';
export const DELETE_HEADER_ITEM_FAILURE = 'DELETE_HEADER_ITEM_FAILURE';

// Logo Actions
export const FETCH_LOGO_REQUEST = 'FETCH_LOGO_REQUEST';
export const FETCH_LOGO_SUCCESS = 'FETCH_LOGO_SUCCESS';
export const FETCH_LOGO_FAILURE = 'FETCH_LOGO_FAILURE';

export const UPDATE_LOGO_REQUEST = 'UPDATE_LOGO_REQUEST';
export const UPDATE_LOGO_SUCCESS = 'UPDATE_LOGO_SUCCESS';
export const UPDATE_LOGO_FAILURE = 'UPDATE_LOGO_FAILURE'; 